package com.margelo.pictureselector

import android.app.Activity
import com.facebook.react.bridge.ReactApplicationContext
import com.luck.picture.lib.basic.PictureSelector
import com.luck.picture.lib.config.SelectMimeType
import com.luck.picture.lib.entity.LocalMedia
import com.luck.picture.lib.interfaces.OnResultCallbackListener
import com.margelo.nitro.NitroModules
import com.margelo.nitro.core.Promise
import com.margelo.nitro.com.margelo.pictureselector.HybridHybridPictureSelectorSpec
import com.margelo.nitro.com.margelo.pictureselector.MediaAsset
import com.margelo.nitro.com.margelo.pictureselector.MediaType
import com.margelo.nitro.com.margelo.pictureselector.PictureSelectorOptions
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
import kotlin.coroutines.suspendCoroutine

// ─── Nitrogen-generated types ─────────────────────────────────────────────────
// Generated by nitrogen into:
//   nitrogen/generated/android/kotlin/com/margelo/nitro/com/margelo/pictureselector/
//     HybridHybridPictureSelectorSpec.kt  — abstract base class (extends HybridObject)
//     MediaAsset.kt                       — data class
//     PictureSelectorOptions.kt           — data class
//     CropOptions.kt                      — data class
//     CompressOptions.kt                  — data class
//     MediaType.kt                        — enum class
//     PickerTheme.kt                      — enum class
//
// Run `npm run generate` before building.

/**
 * Nitro HybridObject implementation for the Android side.
 *
 * Extends the nitrogen-generated [HybridHybridPictureSelectorSpec] which provides
 * the JSI bridge.
 *
 * No-arg constructor — the [ReactApplicationContext] is obtained lazily from
 * [NitroModules.applicationContext], which is set during Nitro initialisation
 * (before any JS call can reach this object). This allows the C++ factory in
 * NitroPictureSelectorOnLoad.cpp to register us with a zero-argument lambda
 * as required by [HybridObjectRegistry.registerHybridObjectConstructor].
 *
 * Threading contract:
 * - [openPicker] and [openCamera] are called on the JS thread.
 * - PictureSelector.create(...).openGallery() must be called on the Main thread.
 * - We switch to Main via [withContext(Dispatchers.Main)] inside Promise.async.
 */
class HybridPictureSelector : HybridHybridPictureSelectorSpec() {

  // Obtained lazily — NitroModules sets applicationContext during module init,
  // which always happens before the first JS call to openPicker / openCamera.
  private val reactContext: ReactApplicationContext
    get() = NitroModules.applicationContext
      ?: throw PictureSelectorException(
        "UNKNOWN",
        "NitroModules is not yet initialised. Make sure NitroModules is set up in your app."
      )

  // ─────────────────────────────────────────────────────────────────────────
  // Public API
  // ─────────────────────────────────────────────────────────────────────────

  override fun openPicker(options: PictureSelectorOptions): Promise<Array<MediaAsset>> {
    return Promise.async {
      withContext(Dispatchers.Main) {
        val activity = requireActivity()
        val mimeType = PictureSelectorOptionsMapper.toSelectMimeType(options.mediaType)

        suspendCoroutine { cont ->
          PictureSelector.create(activity)
            .openGallery(mimeType)
            .setImageEngine(GlideEngine.createGlideEngine())
            .also { builder ->
              PictureSelectorOptionsMapper.applyGallery(builder, options)
            }
            .forResult(object : OnResultCallbackListener<LocalMedia> {
              override fun onResult(result: ArrayList<LocalMedia>) {
                cont.resume(MediaAssetMapper.map(result))
              }

              override fun onCancel() {
                cont.resumeWithException(
                  PictureSelectorException("CANCELLED", "User cancelled the picker")
                )
              }
            })
        }
      }
    }
  }

  override fun openCamera(options: PictureSelectorOptions): Promise<Array<MediaAsset>> {
    return Promise.async {
      withContext(Dispatchers.Main) {
        val activity = requireActivity()
        // Camera always captures a single item; force image if mediaType == ALL
        val mimeType = when (options.mediaType) {
          MediaType.VIDEO -> SelectMimeType.ofVideo()
          else            -> SelectMimeType.ofImage()
        }

        suspendCoroutine { cont ->
          PictureSelector.create(activity)
            .openCamera(mimeType)
            .also { builder ->
              PictureSelectorOptionsMapper.applyCamera(builder, options)
            }
            .forResult(object : OnResultCallbackListener<LocalMedia> {
              override fun onResult(result: ArrayList<LocalMedia>) {
                cont.resume(MediaAssetMapper.map(result))
              }

              override fun onCancel() {
                cont.resumeWithException(
                  PictureSelectorException("CANCELLED", "User cancelled the camera")
                )
              }
            })
        }
      }
    }
  }

  // ─────────────────────────────────────────────────────────────────────────
  // Helpers
  // ─────────────────────────────────────────────────────────────────────────

  private fun requireActivity(): Activity {
    return reactContext.currentActivity
      ?: throw PictureSelectorException(
        "UNKNOWN",
        "No current Activity available. Ensure the picker is called from a mounted component."
      )
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Typed exception — message becomes the JS Error.message
// ─────────────────────────────────────────────────────────────────────────────

class PictureSelectorException(
  val code: String,
  message: String,
) : Exception(message)
